name: 'Check Commits'
description: 'Validates commit messages'
inputs:
  os:
    description: 'Operating system to run on'
    required: true
  node-version:
    description: 'Node.js version to use'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      if: ${{ github.action_repository != github.repository }}
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Setup cache
      uses: actions/cache@v4
      id: build-${{ inputs.os }}-node-v${{ inputs.node-version }}
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: Ensure Git is installed
      run: |
        which git || (apt-get update && apt-get install -y git)
        git --version
      shell: bash
    - name: Auro Check Commits
      run: npx --package=@aurodesignsystem/auro-cli -- auro cc -l -d
      shell: bash
