name: "Component PR Preview"
description: "Deploy or teardown a single component to/from Surge"

inputs:
  action:
    description: "The action to perform: 'deploy' or 'teardown'"
    required: true
  component:
    description: "The single component to deploy/teardown"
    required: true
  pr-number:
    description: "The PR number for the deployment"
    required: true
  demo-path:
    description: "Directory path for component demos (e.g., 'components/checkbox/demo')"
    required: true
  surge-token:
    description: "Surge token for authentication"
    required: true
  github-token:
    description: "GitHub token for PR comments"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Surge
      shell: bash
      run: npm install -g surge
    - name: Deploy or Teardown
      uses: actions/github-script@v6
      env:
        COMPONENT: ${{ inputs.component }}
        ACTION: ${{ inputs.action }}
        PR_NUMBER: ${{ inputs.pr-number }}
        DEMO_PATH: ${{ inputs.demo-path }}
        SURGE_TOKEN: ${{ inputs.surge-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        script: |
          const { execSync } = require('child_process');
          const fs = require('fs');

          const action = process.env.ACTION;
          const component = process.env.COMPONENT;
          const prNumber = process.env.PR_NUMBER;
          const demoPath = process.env.DEMO_PATH;
          const surgeToken = process.env.SURGE_TOKEN;
          const githubToken = process.env.GITHUB_TOKEN;

          if (action === 'deploy') {
            // Deploy to Surge
            if (fs.existsSync(demoPath)) {
              execSync(`surge ${demoPath} https://auro-formkit-${component}-${prNumber}.surge.sh --token ${surgeToken}`, { stdio: 'inherit' });
              console.log(`Deployed ${component} to Surge`);
              process.exit(0);
            } else {
              console.error(`Directory ${demoPath} does not exist`);
              process.exit(1);
            }
          } else if (action === 'teardown') {
            // Teardown from Surge
            execSync(`surge teardown https://auro-formkit-${component}-${prNumber}.surge.sh --token ${surgeToken}`, { stdio: 'inherit' });
            console.log(`Teared down ${component} from Surge`);
            process.exit(0);
          } else {
            console.error('Invalid action. Use "deploy" or "teardown".');
            process.exit(1);
          }
