name: build-and-test
run-name: Build and Test for ${{ github.ref_name }}
on:
  push:
    branches: [ main, rc/** ]
  pull_request:
    branches: [ main, rc/**, dev ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm clean-install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-node-${{ matrix.node-version }}-${{ github.run_id }}
          path: .
