name: Check PR

on:
  pull_request_review:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  require-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Require Reviewers
        uses: travelperk/label-requires-reviews-action@2.0.3
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          rules_yaml: | # define which PR labels require how many approving reviewers
            "semantic-status: breaking": 2

