name: check-commits

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
  check:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Download and Restore Build Artifact
        uses: ./.github/workflows/download-and-restore-artifact.yml
        with:
          os: ubuntu-latest
          node-version: 22
      - name: Ensure Git is installed
        run: |
          which git || (apt-get update && apt-get install -y git)
          git --version
      - name: Auro Check Commits
        run: npx --package=@aurodesignsystem/auro-cli -- auro cc -l -d
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}