name: check-commits

on:
  workflow_run:
    workflows: [build-and-test]
    types: [completed]
    branches-ignore:
      - 'main'

permissions:
  contents: read

jobs:
  get-artifact:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/download-and-restore-artifact.yml
    with:
      os: ubuntu-latest
      node-version: 22
  check:
    runs-on: ubuntu-latest
    needs: get-artifact
    steps:
      - uses: actions/checkout@v4
      - name: Download and Restore Build Artifact
        uses: ./.github/workflows/download-and-restore-artifact.yml
        with:
          os: ubuntu-latest
          node-version: 22
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Ensure Git is installed
        run: |
          which git || (apt-get update && apt-get install -y git)
          git --version
      - name: Auro Check Commits
        run: npx --package=@aurodesignsystem/auro-cli -- auro cc -l -d
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}