name: check-commits
run-name: Check Commits

on:
  workflow_run:
    workflows: [build-and-test]
    types: [completed]
    branches-ignore:
      - 'main'

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    steps:
      - uses: actions/checkout@v4
      - name: Download and Restore Build Artifact
        uses: ./.github/workflows/download-and-restore-artifact.yml
        with:
          os: ubuntu-latest
          node-version: 22
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Ensure Git is installed
        run: |
          which git || (apt-get update && apt-get install -y git)
          git --version
      - name: Auro Check Commits
        run: npx --package=@aurodesignsystem/auro-cli -- auro cc -l -d
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}