name: download-and-restore-artifact
run-name: Download and Restore Build Artifact

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      node-version:
        required: true
        type: string

jobs:
  download_and_restore:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Set artifact name
        run: echo "ARTIFACT_NAME=build-${{ inputs.os }}-node-v${{ inputs.node-version }}-${{ github.run_id }}" >> $GITHUB_ENV
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Restore build files
        run: |
          rsync -a ${{ env.ARTIFACT_NAME }}/ ./
