name: PR Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches-ignore:
      - 'rc/**'
      - 'main' 

permissions:
  contents: read
  id-token: write # for npm provenance
  pull-requests: write # permission to comment on PRs
  deployments: write # permission to manage deployments

jobs:

  build:
    if: github.event.action != 'closed'
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with:
          os: ubuntu-latest
          node-version: ${{ matrix.node-version }}

  test:
    if: github.event.action != 'closed'
    name: Test
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          os: ubuntu-latest
          node-version: ${{ matrix.node-version }}

  release:
    name: PR Release
    needs: [build, test]
    runs-on: ubuntu-latest
    # Skip on PR close and on release branches
    if: github.event.action != 'closed' && !startsWith(github.ref, 'refs/heads/rc/')
    steps:
        - uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 22
            registry-url: 'https://registry.npmjs.org'
        - name: Setup cache
          uses: actions/cache@v4
          id: build-ubuntu-latest-node-v22
          with:
            path: ./*
            key: build-${{ github.sha }}-22
        - name: Generate PR release version
          run: npx --package=@aurodesignsystem/auro-cli -- auro pr-release -p ${{ github.event.pull_request.number }}
        - name: Publish to NPM
          run: npm publish --registry=https://registry.npmjs.org
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        - name: Comment on PR
          run: |
            PACKAGE_NAME=$(node -p "require('./package.json').name")
            PACKAGE_VERSION=$(node -p "require('./package.json').version")
            gh pr comment ${{ github.event.pull_request.number }} -b "🚀 PR Release Published! \`$PACKAGE_NAME@$PACKAGE_VERSION\` [View on npmjs.com](https://www.npmjs.com/package/$PACKAGE_NAME/v/$PACKAGE_VERSION)"
          env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  check-commits:
    name: Check Commits
    needs: [build, test]
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-commits
        with:
          os: ubuntu-latest
          node-version: 22
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  preview:
    name: Preview
    needs: [build, test]
    runs-on: ubuntu-latest
    # Skip on PR close
    if: github.event.action != 'closed'
    strategy:
      matrix:
        component: ["checkbox", "combobox", "counter", "datepicker", "dropdown", "form", "input", "menu", "radio", "select"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup cache
        uses: actions/cache@v4
        id: build_cache
        with:
          path: ./*
          key: build-${{ github.sha }}-22

      - name: Start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.ACCESS_TOKEN }}
          env: release-${{ matrix.component }}
      - name: Deploy ${{ matrix.component }} to Surge
        uses: "./.github/actions/surge"
        with:
          action: deploy
          component: ${{ matrix.component }}
          pr-number: ${{ github.event.pull_request.number }}
          demo-path: "components/${{ matrix.component }}/demo"
          surge-token: ${{ secrets.AURO_SURGE_TOKEN }}
          github-token: ${{ secrets.ACCESS_TOKEN }}
      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.ACCESS_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

  surge-teardown:
    name: Teardown
    runs-on: ubuntu-latest
    # Only run on PR close
    if: github.event.action == 'closed'
    strategy:
      matrix:
        component: ["checkbox", "combobox", "counter", "datepicker", "dropdown", "form", "input", "menu", "radio", "select"]
    steps:
      - uses: actions/checkout@v4
      - name: Teardown ${{ matrix.component }} from Surge
        uses: "./.github/actions/surge"
        with:
          action: teardown
          component: ${{ matrix.component }}
          pr-number: ${{ github.event.pull_request.number }}
          demo-path: "components/${{ matrix.component }}/demo"
          surge-token: ${{ secrets.AURO_SURGE_TOKEN }}
          github-token: ${{ secrets.ACCESS_TOKEN }}