name: Required Approvals
on:
  pull_request_review:
  pull_request:
    types: [opened, reopened, labeled, unlabeled]
jobs:
  required-approvals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Label required approvals
        uses: lvegerano/label-required-approvals@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/team-approvers.yml
  manage-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: Request Reviewers
      uses: neo-diego-beltran/request-reviewers@v0.0.9

