name: test-and-release

# Controls when the action will run.
# - For PRs: runs tests on any PR to main, rc/**, or dev branches
# - For pushes: runs tests and (if successful) the release job, but only on main and rc/** branches
on:
  push:
    branches: [ main, rc/** ]
  pull_request:
    branches: [ main, rc/**, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/rc/'))
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Download and Restore Build Artifact
        uses: ./.github/workflows/download-and-restore-artifact.yml
        with:
          os: ubuntu-latest
          node-version: 22
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
